# Generated by Django 4.2.3 on 2023-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0002_alter_borrowing_actual_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
