# Generated by Django 4.2.3 on 2023-07-06 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowings', '0003_alter_borrowing_actual_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing', to='books.book'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
