# Generated by Django 4.2.3 on 2023-07-07 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0004_alter_borrowing_book_id_alter_borrowing_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=50)),
                ('type', models.CharField(choices=[('Payment', 'Payment'), ('Fine', 'Fine')], max_length=50)),
                ('session_url', models.CharField(blank=True, max_length=500, null=True)),
                ('session_id', models.CharField(blank=True, max_length=500, null=True)),
                ('to_pay', models.DecimalField(decimal_places=2, max_digits=4)),
                ('borrowing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowings.borrowing')),
            ],
        ),
    ]
