# Generated by Django 4.2.3 on 2023-07-08 16:30

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "fixture_data.json")


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0006_alter_payment_to_pay'),
        ("sessions", "0001_initial"),
        ("django_celery_beat", "0018_improve_crontab_helptext")
    ]

    operations = [
        RunPython(func, reverse_func)
    ]
